# Generated by Django 2.0.6 on 2018-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterwaveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaylist',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
